# Generated by Django 4.1.1 on 2022-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Data', '0003_rename_image_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infor_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('picz', models.FileField(upload_to='bio_image/')),
            ],
        ),
    ]
