# Generated by Django 4.1.1 on 2022-12-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_Data', '0004_infor_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='user',
            new_name='password',
        ),
    ]
