# Generated by Django 4.1.1 on 2022-12-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Data', '0005_rename_user_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
